name: Validate generated table of contents

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  gen-toc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate table of contents
        run: pnpm run gen
      - name: Verify generated table of contents is current
        run: git diff --exit-code -- README.md
